Numpy stands for numerical python 
it is the backbone of all kinds of scientific and numerical computing in python

numpy is a python library for the python language, it offers comprehensive maths functions, random number generators, linear algebra routines, fourier transforms and more

since ML is all about turning data into numbers and then figuring out the patterns, Numpy often comes into play

Pandas is an opensource library that helps you analyse and manipulate data.

It is a fast, powerful, flexible, and easy to use open source data analysis and manipulation tool, built on top of the Python programming language. 

One the main use cases you will come across is using pandas to transform your data in a way which makes it usable with ML algorithms

In [3]:
#numpy data types and attributes

import numpy as np

numpy's main data type is nd array
we can define a nd array as the collection of the data type (dtype) objects

In [10]:
#1d array -> vector
a1 = np.array([1,2,3])
#shape is (1,3)

#2d array -> matrix
#passing a list containing lists
a2 = np.array([[1,2,3],[4,5,6]])
#shape is (2,3)



#3d array -> matrix
#passing a list containing lists
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,9,8],[7,6,5],[4,3,2]]])
#shape is (2,3,3)

In [11]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [12]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [13]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [14]:
#create an array
s_array = np.array((1,2,3))

In [15]:
s_array

array([1, 2, 3])

In [17]:
#array of value ones

o = np.ones((4,2))
o

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
#array of value zeroes

z = np.zeros((2,3,3))
z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
#random array float

r_array = np.random.random((2,2))
r_array

array([[0.19642114, 0.05715054],
       [0.32260305, 0.15729507]])

In [23]:
#random array int

r_array = np.random.randint(4, size = (2,2))
r_array

array([[1, 1],
       [3, 1]])

In [25]:
#set random seed to 0

#setting np.random.seed() ensures there is still randomness, it just makes randomness repeatable, the same random numbers will be generated.
#hence the 'pseudolabel'

na = np.random.seed(0)

In [28]:
np.random.randint(10,size=(5,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [29]:
np.random.seed(0)
import pandas as pd
#you can make a dataframe using numpy array of any ndim
df = pd.DataFrame(np.random.randint(10,size=(5,3)))
df

0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

In [ ]:
#view arrays and matrices we use INDEXING
#array shapes are always listed in the format (row,column,n,n,....) 
# n is optional extra dimensions

In [30]:
a1

array([1, 2, 3])

In [31]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10,  9,  8],
        [ 7,  6,  5],
        [ 4,  3,  2]]])

In [33]:
a1[0]

1

In [34]:
a2[0]

array([1, 2, 3])

In [36]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a2[1]

array([4, 5, 6])

In [38]:
#get the first 2 values of the first 2 rows of both arrays
#1. row
#2. column
#3. dimension
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10,  9],
        [ 7,  6]]])

In [39]:
a4 = np.random.randint(10,size = (2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [40]:
a4.shape

(2, 3, 4, 5)

In [41]:
#aggregation
a1

array([1, 2, 3])

In [42]:
np.sum(a1)

6

In [43]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.mean(a2)

3.5

In [45]:
np.max(a2)

6

In [47]:
np.min(a2)

1

In [48]:
np.std(a2)

1.707825127659933

In [49]:
a2.shape

(2, 3)

In [50]:
a2+a3
#cannot add two different shapes

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [51]:
a3.shape

(2, 3, 3)

In [52]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [53]:
a2.reshape(2,3,1)+a3

array([[[ 2,  3,  4],
        [ 6,  7,  8],
        [10, 11, 12]],

       [[14, 13, 12],
        [12, 11, 10],
        [10,  9,  8]]])

In [54]:
a2.T #switches the axis

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
a2.T.shape

(3, 2)

In [58]:
#Dot product

np.random.seed(0)

m1 = np.random.randint(10,size=(5,3))
m2 = np.random.randint(10,size=(5,3))

In [59]:
m1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [60]:
m2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [61]:
m1.shape, m2.shape

((5, 3), (5, 3))

In [62]:
#dot product
np.dot(m1,m2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [65]:
#dimensions must be same to do dot product so we can do transpose here

s = m1.T

In [66]:
s.shape, m2.shape

((3, 5), (5, 3))

In [67]:
m3 = np.dot(s,m2)

In [68]:
m3

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [69]:
#np.random.seed(0)

#number of jars sold

sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[18,  3, 17],
       [19, 19, 19],
       [14,  7,  0],
       [ 1,  9,  0],
       [10,  3, 11]])

In [70]:
#create weeklysales dataframe

df1 = pd.DataFrame(sales_amounts,index=['Mon','Tues','Wed','Thur','Fri'],columns=['almond butter','peanut butter','cashew butter'])

In [71]:
df1

almond butter  peanut butter  cashew butter
Mon              18              3             17
Tues             19             19             19
Wed              14              7              0
Thur              1              9              0
Fri              10              3             11

In [72]:
#prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [73]:
#create butter prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3),index = ['Price'],columns=['almond butter','peanut butter','cashew butter'])

butter_prices


almond butter  peanut butter  cashew butter
Price             10              8             12

In [76]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([408, 570, 196,  82, 256])

In [78]:
#create daily_sales
butter_prices.shape, df1.shape

((1, 3), (5, 3))

In [79]:
df1.T.shape

(3, 5)

In [81]:
daily_sales = butter_prices.dot(df1.T)
daily_sales.shape

(1, 5)

In [82]:
df1

almond butter  peanut butter  cashew butter
Mon              18              3             17
Tues             19             19             19
Wed              14              7              0
Thur              1              9              0
Fri              10              3             11

In [84]:
#add another column to df
df1['Total ($)'] = daily_sales.T
df1


almond butter  peanut butter  cashew butter  Total ($)
Mon              18              3             17        408
Tues             19             19             19        570
Wed              14              7              0        196
Thur              1              9              0         82
Fri              10              3             11        256

Pandas, Datatypes

Pandas has 2 main datatypes, Series, DataFrame

1. Series - 1d array
2. DataFrame - nd array or most commonly a table of 2d array with rows and columns

You can create a series using pd.Series() and passing a python list

You can create a dataframe using pd.DataFrame() and passing a python dictionary

In [86]:
import pandas as pd

#creating a series of car types
car_types = ['BMW','Toyoya','Honda']
ct = pd.Series(car_types)
ct

0       BMW
1    Toyoya
2     Honda
dtype: object

In [88]:

#creating a series of color types
col_types = ['red','green','orange']
ct1 = pd.Series(col_types)
ct1

0       red
1     green
2    orange
dtype: object

In [90]:
#creating a dataframe of cars and colors
car_dict = {'car_type':car_types,'color':col_types}
car_data = pd.DataFrame(car_dict)
car_data

car_type   color
0      BMW     red
1   Toyoya   green
2    Honda  orange

In [92]:
#access columns using index
car_columns = car_data.columns
car_columns

Index(['car_type', 'color'], dtype='object')

In [93]:
car_columns[1]

'color'

In [94]:
car_data.index

RangeIndex(start=0, stop=3, step=1)

In [95]:
#length of dataframe
len(car_data)

3

In [ ]:
#use loc when you are referrring to indexes
#use iloc when you are referring to positions in the dataframe 

In [ ]:
#select cars with over 100,000 odometer
car_sales[car_sales['odometer']>100000]

In [ ]:
#select cars that are mady by toyota
car_sales[car_sales['make']=='Toyota']

In [ ]:
#pd.crosstab() is a great way to view 2 different columns together and compare them


pd.crosstab(car_sales['make'],car_sales['doors'])

In [96]:
#if you want to compare a column with other columns on the basis of like mean use groupby

car_sales.groupby(['make']).mean()

NameError: name 'car_sales' is not defined

In [ ]:
car_sales['odometer'].fillna(car_sales['odometer'].mean(),inplace=False)

In [ ]:
#creating a new column by generating own data
#create a list and feed it to below equation
car_sales['engine_size'] = (list_name)
#or put only a standard value for all rows
car_sales['engine_size'] = 4

In [97]:
#remove a column using drop()

car_sales1 = car_sales.drop("engine size",axis=1)

NameError: name 'car_sales' is not defined